apiVersion: metallb.io/v1beta1
kind: Layer2Configuration
metadata:
  name: config
  namespace: metallb-system
spec:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.0.240-192.168.0.250
